Name:           ros-hydro-object-recognition-reconstruction
Version:        0.3.4
Release:        0%{?dist}
Summary:        ROS object_recognition_reconstruction package

Group:          Development/Libraries
License:        BSD
URL:            http://wg-perception.github.io/reconstruction/
Source0:        %{name}-%{version}.tar.gz

Requires:       meshlab
Requires:       ros-hydro-ecto
Requires:       ros-hydro-ecto-image-pipeline
Requires:       ros-hydro-ecto-pcl
Requires:       ros-hydro-object-recognition-core
Requires:       ros-hydro-opencv-candidate
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-cmake-modules
BuildRequires:  ros-hydro-ecto
BuildRequires:  ros-hydro-ecto-image-pipeline
BuildRequires:  ros-hydro-ecto-pcl
BuildRequires:  ros-hydro-object-recognition-core
BuildRequires:  ros-hydro-opencv-candidate
BuildRequires:  ros-hydro-sensor-msgs

%description
basic 3d reconstruction of an object from aligned Kinect data

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Mon Apr 20 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.3.4-0
- Autogenerated by Bloom

