Name:           ros-kinetic-object-recognition-reconstruction
Version:        0.3.6
Release:        0%{?dist}
Summary:        ROS object_recognition_reconstruction package

Group:          Development/Libraries
License:        BSD
URL:            http://wg-perception.github.io/reconstruction/
Source0:        %{name}-%{version}.tar.gz

Requires:       meshlab
Requires:       ros-kinetic-ecto
Requires:       ros-kinetic-ecto-image-pipeline
Requires:       ros-kinetic-ecto-pcl
Requires:       ros-kinetic-object-recognition-core
Requires:       ros-kinetic-opencv-candidate
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-cmake-modules
BuildRequires:  ros-kinetic-ecto
BuildRequires:  ros-kinetic-ecto-image-pipeline
BuildRequires:  ros-kinetic-ecto-pcl
BuildRequires:  ros-kinetic-object-recognition-core
BuildRequires:  ros-kinetic-opencv-candidate
BuildRequires:  ros-kinetic-sensor-msgs

%description
basic 3d reconstruction of an object from aligned Kinect data

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sat Apr 30 2016 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.3.6-0
- Autogenerated by Bloom

